# Header

menu:
  主页: /
  随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/strongant"
  weibo: "http://weibo.com/xiaomayibwh"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/strongant/activities"
  #qq: "877798942"
  #weixin: "18215361994"
  jianshu: "http://www.jianshu.com/u/30c2d37f8602"
  douban: "https://www.douban.com/people/strongant/"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  google: "https://plus.google.com/u/0/103479297958011311682"
  twitter: "https://twitter.com/java_small_ant"
  linkedin: "https://www.linkedin.com/in/%E6%96%87%E8%BE%89-%E7%99%BD-820a86a0/"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/wechatpay.jpg

# Miscellaneous
baidu_analytics: '86c67d891e2b7fa3f077e18cf34b9435'
google_analytics: 'UA-87429933-2'
favicon: /favicon.ico

#你的头像url

#avatar: https://avatars3.githubusercontent.com/u/7685936?v=3&s=460
avatar: /img/ant.jpeg
#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
duoshuo: true
changyan_appid: 'cysHzQGmj'
changyan_conf: 'prod_25363bfe21a9a09909208a01135582ea'
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: false
# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  泥瓦匠BYSocket: http://www.bysocket.com/
  程序员DD: http://blog.didispace.com/
  周立: http://www.itmuch.com/
  孙亮亮: http://sunliangliang.com/
  王宇宙: https://wayzo.github.io/
  数据结构和算法: https://www.cs.usfca.edu/~galles/visualization/Algorithms.html
  可视化数据结构算法理解: http://algo-visualizer.jasonpark.me/#path=backtracking/knight's_tour/basic
  覃超数据结构和算法加强: https://yuba.douyu.com/qincha
  开源编程学习书籍: https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md
  开源中文学习书籍: https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-zh.md
  web全栈导航: http://webfullstack.me/
  CMU15213: https://www.cs.cmu.edu/~213/
  CMU15410: http://www.cs.cmu.edu/~410/
  #友情链接2: http://localhost:4000/
 # 友情链接3: http://localhost:4000/
  #友情链接4: http://localhost:4000/
  #友情链接5: http://localhost:4000/
  #友情链接6: http://localhost:4000/

aboutme:  
  白文辉
  <br/>
  Java开发工程师，3年相关开发经验，现在就职于好车伯乐(上海优与汽车科技有限公司)。
  <br/>
  技能
  <br/>
  Java开发
  <br/>
  略懂groovy，python，NodeJS等
  <br/>
  工作经历
  <br/>
  1. 上海优与汽车科技有限公司 Java开发
  <br/>
  2. 上海浦东软件园信息技术有限公司Java开发
  <br/>
  3. 兰州中林智能科技有限公司Java开发
  <br/>
  <br/>
  链接
  <br/>
  GitHub - https://github.com/strongant/
  <br/>
  我的博客 - https://strongant.github.io/
  <br/>
  SpringForAll - http://spring4all.com/people/strongant
  <br/>
  联系方式
  <br/>
  微信 18215361994
  <br/>
  邮箱 
  <br/>
  18215361994@163.com  
  <br/>
  bstrongant@gmail.com


