language: node_js
node_js:
- 12.14.0
branches:
  only:
  - hexo
cache:
  directories:
  - node_modules
before_script:
- git config --global user.name 'strongant'
- git config --global user.email '877798942@qq.com'
install:
- npm install hexo-cli -g
- npm install
script:
- hexo -version
- hexo clean
- hexo g
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m master
- git push -q -u origin master
