---

- name: etcd_back | Creating directory
  file:
    path: /opt/etcd_back
    state: directory
    mode: 0755

- name: etcd_back | Getting script
  template:
    src: "{{ item.file }}.j2"
    dest: "/opt/etcd_back/{{ item.file }}"
  with_items:
    - { name: etcd_backup, file: etcd_backup.sh, type: bash }

- name: etcd_back | Change script mode
  file:
    path: /opt/etcd_back/etcd_backup.sh
    mode: 0755

- name: periodic backup (etcd)
  cron:
    name: "periodic backup (etcd)"
    minute: "*/{{ etcd_backup_period }}"
    job: "/opt/etcd_back/etcd_backup.sh"