---
- name: Fetch /etc/os-release
  raw: cat /etc/os-release
  register: os_release
  changed_when: false
  environment: {}

- name: Create kube pip dir
  file:
    path: "/tmp/pip"
    mode: "0700"
    state: directory

- name: Copy get-pip.py
  copy:
    src: "get-pip.py"
    dest: "/tmp/pip/get-pip.py"
    mode: "0700"  

- name: Copy pip.conf
  copy:
    src: "pip.conf"
    dest: "/tmp/pip/pip.conf"
    mode: "0700"    

- name: pip | Installing pip
  shell: sudo python /tmp/pip/get-pip.py
  
- name: GlusterFS | Installing pyOpenSSL
  pip: 
    name: pyOpenSSL
    version: 18.0.0
  register: result
  until: result is succeeded
  retries: 5
  delay: 5
  when: ansible_os_family in ["Ubuntu", "Debian"]

- name: GlusterFS | add glusterfs-client repository (APT)
  apt_repository:
    repo: ppa:gluster/glusterfs-3.12
  register: result
  until: result is succeeded
  retries: 5
  delay: 5
  when: '"Ubuntu" in os_release.stdout'

- name: GlusterFS | add glusterfs-client apt_key (APT)
  apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/01.old-releases/3.12/rsa.pub
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 5
  when: '"Debian" in os_release.stdout'

- name: GlusterFS | add glusterfs-client repository (APT)
  shell: >
    DEBID=$(grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '"') &&
    DEBVER=$(grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+') &&
    DEBARCH=$(dpkg --print-architecture) &&
    echo deb https://download.gluster.org/pub/gluster/glusterfs/01.old-releases/3.12/LATEST/Debian/${DEBID}/${DEBARCH}/apt ${DEBVER} main > /etc/apt/sources.list.d/gluster.list
  when: '"Debian" in os_release.stdout'

- name: GlusterFS | Installing glusterfs-client (APT)
  apt:
    name: glusterfs-client
    update_cache: yes
  register: result
  until: result is succeeded
  retries: 5
  delay: 5
  when: ansible_os_family in ["Ubuntu", "Debian"]

- name: GlusterFS | Installing glusterfs-client (YUM)
  yum:
    name: glusterfs-client
  register: result
  until: result is succeeded
  retries: 5
  delay: 5
  when: ansible_os_family in ["RedHat", "Centos"]