---

etcd_backup_period: 30
keep_backup_number: 5

etcd_backup_dir: "/var/backups/kube_etcd"
etcd_backup_prefix: "{{ etcd_backup_dir }}"

etcd_config_dir: /etc/ssl/etcd
etcd_cert_dir: "{{ etcd_config_dir }}/ssl"

etcd_endpoint: |-
  {% for item in groups['etcd'] -%}
    {{ hostvars[item]['access_ip'] | default(hostvars[item]['ip'] | default(hostvars[item]['ansible_default_ipv4']['address'])) }}:2379{% if not loop.last %},{% endif %}
  {%- endfor %}


